### ISSUE TITLE
Loading the local model will report an error

### ISSUE THREAD

**Issue by Orangeices** [WeiNyn/DIETClassifier-pytorch#1]
```
Traceback (most recent call last):
  File "D:/pycharm/DIETClassifier-pytorch-main/main.py", line 5, in <module>
    from demo.server import app
  File "D:\pycharm\DIETClassifier-pytorch-main\demo\server.py", line 15, in <module>
    wrapper = DIETClassifierWrapper(CONFIG_FILE)
  File "D:\pycharm\DIETClassifier-pytorch-main\src\models\wrapper.py", line 62, in __init__
    self.model = DIETClassifier(config=self.model_config)
  File "D:\pycharm\DIETClassifier-pytorch-main\src\models\classifier.py", line 57, in __init__
    self.entities_list = ["O"] + config.entities
AttributeError: 'PretrainedConfig' object has no attribute 'entities'
```

**Comment by Orangeices** [comment]
```
if path.exists(config.model):
    try:
        json_config = json.load(open(f"{config.model}/config.json", "r"))
        # json_config.update({"model": config.model, "entities": config.entities, "intents": config.intents})
```
### Add this line of comment code, the last problem can be solved. BUT:
`RuntimeError: Cannot load state dict from checkpoint by error: Error(s) in loading state_dict for DIETClassifier:`

**Comment by WeiNyn** [comment]
please give me more information about your config file

**Comment by Orangeices** [comment]
@WeiNyn I use Pycharm
my config file：
only modify
```
model:
  model: "F:/BaiduNetdiskDownload/huggingface_models/bert-base-uncased"
  tokenizer: "F:/BaiduNetdiskDownload/huggingface_models/bert-base-uncased"
  dataset_folder: "D:/pycharm/DIETClassifier-pytorch-main/dataset"

```


I run this file directly: `classifier.py`.
used absolute path.  I downloaded `bert-base-uncased`
```
    files = [r"D:\pycharm\DIETClassifier-pytorch-main\dataset\nlu_QnA_converted.yml",
             r"D:\pycharm\DIETClassifier-pytorch-main\dataset\nlu_converted.yml"]
    # tokenizer = AutoTokenizer.from_pretrained("dslim/bert-base-NER")
    tokenizer = AutoTokenizer.from_pretrained(r"F:\BaiduNetdiskDownload\huggingface_models\bert-base-uncased")

    df, entities_list, intents_list, synonym_dict = make_dataframe(files)
    dataset = DIETClassifierDataset(dataframe=df, tokenizer=tokenizer, entities=entities_list, intents=intents_list)

    config = DIETClassifierConfig(
        model=r"F:\BaiduNetdiskDownload\huggingface_models\bert-base-uncased",
        entities=entities_list,
        intents=intents_list
    )
```

- directory `bert-base-uncased`
  - config.json
  - pytorch_model.bin
  - tokenizer.json
  - tokenizer_config.json
  - vocab.txt

**Comment by WeiNyn** [comment]
> @WeiNyn I use Pycharm
> my config file：
> only modify
> 
> ```
> model:
>   model: "F:/BaiduNetdiskDownload/huggingface_models/bert-base-uncased"
>   tokenizer: "F:/BaiduNetdiskDownload/huggingface_models/bert-base-uncased"
>   dataset_folder: "D:/pycharm/DIETClassifier-pytorch-main/dataset"
> ```
> 
> I run this file directly: `classifier.py`.
> used absolute path. I downloaded `bert-base-uncased`
> 
> ```
>     files = [r"D:\pycharm\DIETClassifier-pytorch-main\dataset\nlu_QnA_converted.yml",
>              r"D:\pycharm\DIETClassifier-pytorch-main\dataset\nlu_converted.yml"]
>     # tokenizer = AutoTokenizer.from_pretrained("dslim/bert-base-NER")
>     tokenizer = AutoTokenizer.from_pretrained(r"F:\BaiduNetdiskDownload\huggingface_models\bert-base-uncased")
> 
>     df, entities_list, intents_list, synonym_dict = make_dataframe(files)
>     dataset = DIETClassifierDataset(dataframe=df, tokenizer=tokenizer, entities=entities_list, intents=intents_list)
> 
>     config = DIETClassifierConfig(
>         model=r"F:\BaiduNetdiskDownload\huggingface_models\bert-base-uncased",
>         entities=entities_list,
>         intents=intents_list
>     )
> ```
> 
> * directory `bert-base-uncased`
>   
>   * config.json
>   * pytorch_model.bin
>   * tokenizer.json
>   * tokenizer_config.json
>   * vocab.txt

Please replace the Model and tokenizer path by "bert-base-uncased", it will automatically download from huggingface

**Comment by Orangeices** [comment]
thanks！！
