### ISSUE TITLE
CUDA error:  device-side assert triggered

### ISSUE THREAD

**Issue by DhineshKS04** [WeiNyn/DIETClassifier-pytorch#2]
When I added some new intents and entities in nlu.yml and ran wrapper.py triggering train_model(). this arises with error below.

/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "src/classification/wrapper.py", line 243, in <module>
    wrapper.train_model()
  File "src/classification/wrapper.py", line 227, in train_model
    trainer.train()
  File "/mnt/e/intellemo/official/chat-nlp-aiapi/src/classification/trainer.py", line 52, in train
    self.trainer.train()
  File "/mnt/e/intellemo/official/chat-nlp-aiapi/algosrc/lib/python3.8/site-packages/transformers/trainer.py", line 1280, in train
    tr_loss += self.training_step(model, inputs)
  File "/mnt/e/intellemo/official/chat-nlp-aiapi/algosrc/lib/python3.8/site-packages/transformers/trainer.py", line 1773, in training_step
    loss = self.compute_loss(model, inputs)
  File "/mnt/e/intellemo/official/chat-nlp-aiapi/algosrc/lib/python3.8/site-packages/transformers/trainer.py", line 1805, in compute_loss
    outputs = model(**inputs)
  File "/mnt/e/intellemo/official/chat-nlp-aiapi/algosrc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/e/intellemo/official/chat-nlp-aiapi/src/classification/classifier.py", line 143, in forward
    entities_loss = entities_loss_fct(active_logits, active_labels)
  File "/mnt/e/intellemo/official/chat-nlp-aiapi/algosrc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/e/intellemo/official/chat-nlp-aiapi/algosrc/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1120, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/mnt/e/intellemo/official/chat-nlp-aiapi/algosrc/lib/python3.8/site-packages/torch/nn/functional.py", line 2824, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: CUDA error: device-side assert triggered
  0%|                                                                                                                            | 2/22600 [00:01<4:19:44,  1.45it/s]

Is that something that i need to increase  the number of labels?

**Comment by WeiNyn** [comment]
RuntimeError: CUDA error: device-side assert triggered usually caused by the different in input and label dimension, please check the shape of your input, label, and model layers.

**Comment by DhineshKS04** [comment]
@WeiNyn  What I did is that I added new intents like my_name_is , mobile_number and entities like (PERSON) , (phonenumber) in nlu.yml .  And also added this new set of intents and entities in config.yml. while running wrapper.py the error arises. I found that at line number 54 and 56 in classifier.py the newly added intents and entities are not updating so this not changing hidden size. 

A pretrained weight and configurations are used, so it is a transfer learning method right?  So the newly added intents and entities are not updating.

I am new to this. Help me in this issue. Am I done anything wrong?

**Comment by DhineshKS04** [comment]
@WeiNyn  I figured out to solve the issue. Thanks!!

**Comment by WeiNyn** [comment]
@DhineshKS04 Could you please tell the cause, it might help the other.

**Comment by DhineshKS04** [comment]
@WeiNyn  Yes, As my intention is to train model on new set of data. so I updated new set of intents and entities in nlu.yml. so by default the config.yml values are set at inference/demo level. Then I changed some of the values in cofig.yml like model and tokenizer,

model:
  model: "dslim/bert-base-NER"
  tokenizer: "dslim/bert-base-NER"
  dataset_folder: utils
  exclude_file: null
  entities:
  - working_type
  - shift_type
  - org
  - PERSON
  - phonenumber
  intents:
  - WorkTimesBreaches
  - WorkingTimeBreachDiscipline
  - HolidaysOff
  - AnnualLeaveApplicationProcess
  - SetWorkingType
  - TemporarySetWorkingType
  - WorkingHours
  - WorkingDay
  - BreakTime
  - Pregnant
  - AttendanceRecord
  - SelectShiftType
  - LaborContract
  - Recruitment
  - SickLeave
  - UnpaidLeave
  - PaidLeaveForFamilyEvent
  - UnusedAnnualLeave
  - RegulatedAnnualLeave
  - rating
  - spent_platform
  - my_name_is
  - mobile_number
  - greet
  - goodbye
  - affirm
  - deny
  device: cuda
  synonym:
    office hour: office hours
    office: office hours
    office hours: office hour
training:
  train_range: 0.95
  num_train_epochs: 100
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  warmup_steps: 500
  weight_decay: 0.01
  logging_dir: logs/
  early_stopping_patience: 10
  early_stopping_threshold: 0.0001
  output_dir: results/
util:
  intent_threshold: 0.7
  entities_threshold: 0.5
  ambiguous_threshold: 0.2

using "dslim/bert-base-NER" for model and tokenizer.
So you see that some new set of entities and intents were added. At first the classifier is taking config.json and pretrained weight  from the folder latest_model. so, the new set of intents and entities are not updated in the hidden size and that causes the error.

**Comment by WeiNyn** [comment]
@DhineshKS04 I see your problem, you can use the pre-trained model with custom intents and entities by modifying the config.json file in the model folder (download from the google drive link).
BTW, thank you for your very detailed information.
