### ISSUE TITLE
bug when training model

### ISSUE THREAD

**Issue by namlh16** [WeiNyn/DIETClassifier-pytorch#4]
i got this error when training model. but i don;t know how to fix this. please help
![Screenshot from 2021-10-05 20-54-55](https://user-images.githubusercontent.com/51730208/136037419-c2265f96-b4de-42d7-a1c8-34ec9eda3cc2.png)

**Comment by WeiNyn** [comment]
try to add argument: save_strategy = 'epoch' at TrainingArguments line 27 of src/model/trainer.py
